name: Clans
version: '1.6.1'
main: tech.flubel.clans.Clans
api-version: 1.13
authors: [ MrFiend179 ]
softdepend: [Fcore]
website: 'https://flubel.com'
description: Create Clans for Survival
commands:
  clan:
    description: Clan commands
    usage: /clan <usage> <clan_name>
    aliases: [c]
  cc:
    description: Sends a message to the clan chat.
    usage: /cc <message>